### ISSUE TITLE
cannot convert to .loom from-cellranger

### ISSUE THREAD

**Issue by Eneritz** [linnarsson-lab/loom-viewer#100]
Hi,
I am trying to convert 10X data to loom file. 
I already did it with some previous version, now with the new version I cannot.

- I do not get any error, but the output folder is empty
- Did the command line usage change? ( I was doing the conversion through command line)
- as input I use the input for ( -i ../outs/ ) and out folder ( -o ../file.loom )
- my data is in GRCh38  

loom v0.22.26

thanks
E

**Comment by pl-ki** [comment]
This should be solved in code now. Use updated loompy package or velocyto on commandline.
