### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loom-viewer#128]
Sten, just a quick check: I assume we'll use the same licence as [`loompy`](https://github.com/linnarsson-lab/loompy/blob/master/LICENSE), that is: BSD 2-clause "Simplified" License"? If so I'll just copy that.

**Comment by slinnarsson** [comment]
Yes sure. Simple as possible.

Sten

--
Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet
Unit of Molecular Neurobiology
Department of Medical Biochemistry and Biophysics
Scheeles väg 1, 171 77 Stockholm, Sweden<x-apple-data-detectors://1/0>
+46 8 52 48 75 77<tel:+46%208%2052%2048%2075%2077> (office)
+46 70 399 32 06<tel:+46%2070%20399%2032%2006> (mobile)

20 okt. 2017 kl. 16:36 skrev Job van der Zwan <notifications@github.com<mailto:notifications@github.com>>:


Sten, just a quick check: I assume we'll use the same licence as loompy<https://github.com/linnarsson-lab/loompy/blob/master/LICENSE>, that is: BSD 2-clause "Simplified" License"? If so I'll just copy that.

**Comment by JobLeonard** [comment]
Ok, apologies for the noise, I just tried adding it and then noticed that you already added this license file two years ago. Somehow missed it when I looked for it earlier.
