### ISSUE TITLE
Question regarding Loom CLI

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loom-viewer#129]
Am I correct in understanding that the `loom` CLI tool is officially deprecated, not maintained, and not used anywhere in the pipeline other than serving the viewer? Does that mean I can safely strip anything non-viewer related, so stuff like creating Loom files from other files, uploading to a server, using BackSPIN, and so on?

I'd like to do some code clean-up on the Python side of the `loom-viewer` code, and there's a lot of old stuff I haven't looked at in over a year and I don't know what is and isn't relevant at this stage.

**Comment by slinnarsson** [comment]
Yes, correct. The only use for it now is to extract loom files for the server.

/Sten

-- 
Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet 
Unit of Molecular Neurobiology 
Department of Medical Biochemistry and Biophysics 
Scheeles väg 1, 171 77 Stockholm, Sweden
+46 8 52 48 75 77 (office)
+46 70 399 32 06 (mobile)

**Comment by JobLeonard** [comment]
Time to do some ~~spring~~ autumn cleaning!

**Comment by JobLeonard** [comment]
I assume `loom_pipeline.py` can be deleted as a whole?
