### ISSUE TITLE
Flask fixes with multiple connections

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loom-viewer#83]
@slinnarsson, this seems relevant to our Flask problems:

http://stackoverflow.com/questions/39806848/how-to-stop-persistent-connections-in-flask
> Flask becomes unresponsive when two or more different client send requests at the same time. I tested other possibilities very extensively and can quite confidently say that the problem is being caused due to persistent connections. If I close the one of the two connections Flask immediately becomes responsive again and other request is served.

Which links to the following SO thread with two replies that might give some hints for how to fix our issues:
http://stackoverflow.com/questions/12591760/flask-broken-pipe-with-requests

> Run your flask app under a proper WSGI server capable of handling concurrent requests (perhaps gunicorn or uWSGI) and it'll work. While developing, enable threads in the Flask-supplied server with:
>
> `app.run(threaded=True)`

**Comment by mohit3wadhwa** [comment]
HI,
I am having the same issue but I am unable to follow.
Can you please let me know what exactly you did to fix this issue?

Thanks,
Mohit Wadhwa

**Comment by naveeen684** [comment]
I can't do multiple login in my flask app? Please anybody have solution
